== Introdução 

Antes de tudo: bem-vindo à comunidade Starling!
Desde o seu primeiro lançamento em 2011, desenvolvedores do mundo inteiro criaram apps e jogos incríveis com a ajuda do pequeno pássaro vermelho.
É ótimo ter você conosco!

Você veio ao lugar certo: Este manual te ensinará tudo o que você precisa saber.
Nós cobriremos tudo de 'A' como _Animação_ até 'Z' como, hmm, _Zelar por um bom código_.

Eu iniciarei do zero, começando com um pequeno jogo que te dará uma introdução ao framework.
Então nós veremos em detalhes todos os conceitos, incluindo a arquitetura da lista de exibição e o sistema de animação do Starling.
Os capítulos seguintes contém informações para usuários avançados, como por exemplo como escrever um código personalizado de renderização.
Antes que você perceba, você dominará o Starling!

Entretanto, existe uma pequena condição: você deve ter um entendimento básico sobre _ActionScript 3_ (AS3).
Não tema: se você já usou alguma outra linguagem de programação orientada a objetos, você pegará o jeito rapidamente.
Existem inúmeros livros e tutoriais disponíveis para você começar.

Se você me perguntar por um em particular, eu posso te recomendar o "Essential ActionScript 3" por _Colin Moock_.
Quando eu comecei a trabalhar com AS3, ele me ensinou todos os pontos principais, e eu ainda continuo tirando ele da estante de tempos em tempos (especialmente com a estranha sintaxe E4X para processamento de XML do AS3).

.AS3 vs. JS
****
Você sabia que na verdade o _ActionScript 3_ foi desenhado para se tornar o sucessor do _JavaScript_?
Como você deve saber, _JavaScript_ é uma implementação da especificação da linguagem de programação _ECMAScript_; e o _ActionScript 3_ é baseado no _ECMAScript 4_.
Entretanto, devido principalmente à razões políticas, o _ECMAScript 4_ foi abandonado e nunca se tornou parte dos navegadores; hoje, o _ActionScript 3_ continua como a única implementação do padrão.
Embora, ironicamente, versões modernas do _JavaScript_ se pareçam mais e mais com o _ActionScript 3_.
****

