== O que é o Adobe AIR?
ifndef::imagesdir[:imagesdir: ../../img]

Alguns anos atrás, o Adobe _Flash Player_ era onipresente nas páginas da web.
Nesse tempo, ele era basicamente a única escolha quando você queria criar conteúdos interativos ou animados para a internet.
Navegadores tinham capacidades bem limitadas em vídeo, som, animação e os poucos recursos que eles tinham eram atrapalhados por incompatibilidades dos navegadores.
resumindo: era uma bagunça.

Por isso o _Adobe Flash_ era tão popular.
footnote:[_Flash_ foi originalmente criado pela  _Macromedia_, que foi adquirida pela  Adobe em 2005.]
Ele permitiu designers e desenvolvedores criarem conteúdo multimídia em um programa de criação intuitivo (chamado agora de _Adobe Animate_), e assegurava que ele seria exibido da mesma forma em todas as plataformas.
O _ActionScript 3_ também apresentava uma linguagem que era tanto poderosa quanto fácil de aprender.

Com base na popularidade da sua plataforma, a Adobe percebeu que existia uma demanda para usar a mesma tecnologia para aplicações autônomas que funcionassem fora do navegador.
É para isso que o  _Adobe AIR_ serve.
Aplicações construídas com o _AIR SDK_ podem ser distribuídas como aplicações autônomas que funcionam em computadores (_Windows_ e _macOS_) ou dispositivos móveis (_Android_ e _iOS_).
Sua biblioteca padrão é um superconjunto da usada pelo Flash, portanto você pode fazer qualquer coisa com o _AIR_ que você pode fazer com o _Flash_; mas ele também fornece um grande número de APIs adicionais para coisas como acesso de arquivos do sistema ou gerenciamento de janelas.
Quando você quer criar uma aplicação desktop, você também precisa de uma forma para criar interfaces gráficas de usuários, certo?
Como o Flash padrão não era adequado para essa tarefa, isso foi movido para o _FLEX_ SDK (agora _Apache Flex_).
O Flex também trouxe uma linguagem de marcação baseada em XML (chamada de _MXML_) para definir layouts de interfaces de usuários.

NOTE: Você não precisará do _FLEX_ para usar o Starling, apenas o _AIR SDK_.

=== O estado atual do Flash e do AIR

No momento da sua introdução, o _AIR_ era parte de uma tendência conhecida pelo termo "rich Internet applications" (_RIA_) -- um termo popular que estava na moda no final dos anos 2000.
Existia uma forte competição entre o _AIR_ da Adobe e o _Silverlight_ da Microsoft (assim como o _JavaFX_ da Sun).
No entanto, atualmente fica claro que as marés mudaram.
O evidente vencedor é o _HTML5/JavaScript_, que hoje é o conjunto de tecnologias mais populares para a construção de aplicações com tecnologia para internet.
Mesmo a Adobe tem seguido a tendência e adicionando cada vez mais suporte _HTML5_ para os seus produtos.

TIP: Se tratando de desenvolvimento de software, não caia na armadilha de seguir cegamente ao popular.
Para cada problema, existem muitas soluções; algumas se encaixam melhor do que outras.
Escolha a ferramenta que é mais confortável para você; uma ferramenta que não te atrapalhe e te deixe focar no software que você pretende criar.

Mesmo não sendo mais o "garoto descolado" da cidade, a plataforma _AIR/Flash_ ainda é uma plataforma muito atraente para a construção de softwares.

* Comparado ao mundo fragmentado do _HTML5_, onde bibliotecas que são tendências mudam mais rápido do que as roupas da Lady Gaga, vemos esta plataforma é muito madura e fácil de usar.
* Vem com uma extensa biblioteca que te fornece todas as ferramentas necessárias para o desenvolvimento do dia-a-dia.
* O plug-in Flash, que mesmo em evidente declínio para websites, continua como o padrão para jogos de navegador. A maioria dos jogos do _Facebook_, por exemplo, ainda é feita em Flash.
* Especialmente quando combinado com _Starling_ e _Feathers_, ele fornece uma forma fácil para um verdadeiro desenvolvimento multiplataforma (visando o desenvolvimento de todas as principais plataformas móvel e desktop com um único código base).

Falando sobre o _Starling_ ... como ele entra nessa história?
